### ISSUE TITLE
Question about network architecture?

### ISSUE THREAD

**Issue by Gxinhu** [dimitymiller/cac-openset#5]
Hi,

The paper said `The base network architecture f was consistent with the
architecture established by [13]. It consists of 9 convolutional layers with batch norm after every layer and dropout
after every 3 layers, followed by a fully-connected layer.` in the Supplementary Martials. And I found there exists some differences: the position of dropout.
Comparing with [origin code](https://github.com/lwneal/counterfactual-open-set/blob/34fbc726fb7fe76d15fb323e9597c76292b66d81/generativeopenset/network_definitions.py#L234), your code put dropout at last of each encoder, instead of beginning. I am not familiar with network architecture, so is this will cause any performance differences?

**Comment by dimitymiller** [comment]
Hi @Gxinhu,

We had followed the description in the paper [13] for the architecture, where they state that "Dropout is applied at the end of each block in all networks except the generator." However, as you note, this is different to the public code that they provide which puts dropout at the start of each block. 

I don't think it should cause major performance differences, as dropout is used as a regularisation technique (rather than adding capacity to the network), but I would need to validate this experimentally. Logically, I believe it makes more sense to use dropout at the end of each block for regularisation (applying at the start of each block means that dropout is also applied to raw image pixels). I will check this week and post the difference in results in this issue before I close it.

**Comment by Gxinhu** [comment]
Thanks for looking into this. Looking forward the results.

**Comment by dimitymiller** [comment]
***** Note: these results should not be reported in a paper without doing a proper search for dropout rates that enable the most accurate performance on the validation dataset.*****

If we place dropout at the beginning of each block, without doing a search on optimal dropout rate, we get the following results (mean AUROC and standard deviation):

MNIST: 98.8 ± 0.6
SVHN: 93.4 ± 0.3
CIFAR10: 78.7 ± 3.0
CIFAR+10: 87.2 ± 1.5
CIFAR+50: 86.3 ± 0.6
Tiny ImageNet: 71.8 ± 1.7

Overall, performance remains mostly consistent on MNIST, SVHN, CIFAR10, CIFAR+10 and CIFAR+50, but slightly reduced from placing dropout at the end of each block. These results on these datasets are within the standard deviation bounds though so the difference might not be statistically significant from the previous results. 

Changing the dropout position shows a larger impact on the TinyImageNet results. While we still maintain best performance, the drop in performance appears statistically significant. This seems reasonable - we found that Tiny ImageNet required much greater regularisation in order to learn an accurate network and by moving the dropout to the start of each block, there is limited regularisation on the final classification fully-connected layer. We also did not experiment with different dropout rates that are best for the new dropout position, so that may have had some impact.

Hope this helps!
