### ISSUE TITLE
ValueError: expected sequence of length 2 at dim 1 (got 1)

### ISSUE THREAD

**Issue by starsky68** [dimitymiller/cac-openset#7]
torch.Tensor([[i for i in range(self.cls_num) if gt[x] != i] for x in range(len(distances))])

[[0, 1], [1], [0, 1], [1], [0, 1], [1], [0, 1], [1], [0, 1], [1], [0, 1], [1], [0, 1], [1], [0, 1], [1], [0, 1], [1]]

cacloss输出是这也的list，我知道这个报错是list里不可以[0,1]核[1]同时存在

请问这行的正确输出list应该是什么样子的那？

**Comment by dimitymiller** [comment]
As per google translate: "This is the list. I know that this error is that [0,1] and [1] cannot exist in the list at the same time.May I ask what the correct output list of this line should look like?" Please let me know if the translation has missed anything.

To check - is this line 88 in train_cacOpenset.py ?
`non_gt = torch.Tensor([[i for i in range(cfg['num_known_classes']) if gt[x] != i] for x in range(len(distances))]).long().cuda()`
If not, please let me know which file the line is from.

The correct output list should have a shape of m X n-1 where m is the number of inputs being tested and n is the number of training classes. Essentially, for each input, we collect the indices that are NOT the GT class index. Example:
`self.cls_num = 3
gt = [0, 1, 2]
output = [[1, 2], [0, 2], [0, 1]]`

This error is caused by either having self.cls_num or gt set incorrectly. My guess is that there is self.cls_num = 2 but with gt labels (0, 2)? Instead, your gt labels should be (0, 1). 

If you need more help, please share what self.cls_num is and what gt is when the error occurs.

**Comment by starsky68** [comment]
> As per google translate: "This is the list. I know that this error is that [0,1] and [1] cannot exist in the list at the same time.May I ask what the correct output list of this line should look like?" Please let me know if the translation has missed anything.
> 
> To check - is this line 88 in train_cacOpenset.py ? `non_gt = torch.Tensor([[i for i in range(cfg['num_known_classes']) if gt[x] != i] for x in range(len(distances))]).long().cuda()` If not, please let me know which file the line is from.
> 
> The correct output list should have a shape of m X n-1 where m is the number of inputs being tested and n is the number of training classes. Essentially, for each input, we collect the indices that are NOT the GT class index. Example: `self.cls_num = 3 gt = [0, 1, 2] output = [[1, 2], [0, 2], [0, 1]]`
> 
> This error is caused by either having self.cls_num or gt set incorrectly. My guess is that there is self.cls_num = 2 but with gt labels (0, 2)? Instead, your gt labels should be (0, 1).
> 
> If you need more help, please share what self.cls_num is and what gt is when the error occurs.

Thank you for your reply. My gt is a list of 0 and 1, CLS_ Num = 2, so I modified it to replace it. There is no bug
        non_gt = []
        non_gt_v = []
        for x in range(len(distances)):
            for i in [0,1]:
                if gt[x] != i:
                    non_gt_v.append(i)
            non_gt.append(non_gt_v)

**Comment by dimitymiller** [comment]
This should do the exact same thing that the repo line I posted above does. Either way, glad you have it working.
